# Generated by Django 3.1.1 on 2021-02-20 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Forums', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtopic',
            old_name='subtopic_text',
            new_name='subtopic_name',
        ),
    ]
